### ISSUE TITLE
getProfile without cache service throws with a missing 3id object

### ISSUE THREAD

**Issue by lsenta** [3box/3box-js#339]
**To Reproduce**

In a script:
```js
const Box = require('3box')
const ADDR_OED = '0x258DDD84abf61ba1D1E39f95D8863ee9ca218c06'

const t = async () => {
  const profileCached = await Box.getProfile(ADDR_OED, { useCacheService: true })
  console.error(profileCached)
  const profile = await Box.getProfile(ADDR_OED, { useCacheService: false })
  console.error(profile)
}
t()
```

**Expected behavior**
I expect to get a profile identical to the one retrieved with `useCacheService: true` (default).

**Observed behavior**
An error is thrown:

```
    TypeError: Cannot read property 'getKeyringBySpaceName' of undefined

      231 |             switch (_context5.prev = _context5.next) {
      232 |               case 0:
    > 233 |                 key = this._3id.getKeyringBySpaceName(this._name).getDBKey();
          |                                 ^
      234 |                 _context5.next = 3;
      235 |                 return this._orbitdb.keyvalue(odbAddress || this._name, {
      236 |                   key: key,

      at ProfileStore.getKeyringBySpaceName (../3box-js/lib/keyValueStore.js:233:33)
      at tryCatch (../3box-js/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (../3box-js/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (../3box-js/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (../3box-js/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../3box-js/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at ../3box-js/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
```

**Additional context**

Looks like we create a `ProfileStore` without the 3id parameter:
https://github.com/3box/3box-js/blob/develop/src/3box.js#L222

https://github.com/3box/3box-js/blob/develop/src/publicStore.js#L5

which will break when we call its `_load` method:
https://github.com/3box/3box-js/blob/develop/src/keyValueStore.js#L86

**Comment by oed** [comment]
Nice catch! The getProfile without cache method have not been getting much attention recently.
