### ISSUE TITLE
Cannot find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by joeb000** [3box/3box-js#414]
**Describe the bug**
Trying to run 3box from node js (v10.15.3). Seeing the following when I try to `getProfile`

```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'babel-runtime/regenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/joeb/Workspace/consensys/rapid-eventhub/node_modules/muport-did-resolver/lib/register.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**To Reproduce**
Run the following in a js file with `node`
```
const Box = require('3box')
const main = async () => {
    const joe = '0x068a1a9B6dA95E03b6a2716FdEEe0854117300a3'
    const profile = await Box.getProfile(joe)
    console.log(profile)
}; main();

```

**Comment by oed** [comment]
Hey, so sorry! Seems like we've totally missed this bug report! Is this still a problem for you?
