### ISSUE TITLE
box.auth throws exception with no helpful message

### ISSUE THREAD

**Issue by dkent600** [3box/3box-js#873]
After this:

```
    box = await Box.create(web3Provider);
    await box.auth([spaceName], { address: accountAddress });
```

an exception is thrown, with not much to go on:

> Error: An error occured [sic] while opening space: 
    at Box._callee7$ (webpack-internal:///./node_modules/3box/lib/3box.js:605:23)
    at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.eval [as throw] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _throw (webpack-internal:///./node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9) {stack: 'Error: An error occured while opening space: …bel/runtime/helpers/asyncToGenerator.js:29:9)', message: 'An error occured while opening space: '}

`spaceName` is "DAOstack"
Using 3box@1.20.3

You can reproduce here:  https://alchemy-add3boxcomments-jjgmo6.herokuapp.com/

STEPS:
1. in the upper-right, login to an account (I'm using metamask)
2. hover your mouse over the account address or name and in the dropdown, click "Full Profile"
3. edit and submit the profile.

You'll get prompts to sign, then the error occurs

**Comment by oed** [comment]
Created a PR to address the error message not being very helpful: https://github.com/3box/3box-js/pull/874
